# Generated by Django 5.2.17 on 2026-09-30 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='12 lowercase hex digits of the MAC', max_length=12, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=80)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('fw', models.CharField(blank=True, max_length=30)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_state', models.JSONField(blank=True, default=dict)),
                ('info', models.JSONField(blank=True, default=dict, help_text='Last /api/info (themes, moods)')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='groups', to='devices.device')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.JSONField(blank=True, default=dict, help_text='e.g. {"theme": "sauron", "mood": "angry"}')),
                ('action', models.JSONField(blank=True, help_text='e.g. {"action": "look", "x": -1, "y": 0, "duration": 5}', null=True)),
                ('group', models.ForeignKey(blank=True, help_text='Leave empty to target every board', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
