// Built-in themes. Designated initialisers must follow ThemeSpec's field order.
//
// Design notes for the skull-mount use case: the panels sit behind dark plastic eye sockets,
// so dark surrounds vanish and whatever is bright is the whole eye. Every theme therefore
// leads with a bold, high-contrast silhouette and, where it fits, an emissive glow that reads
// through the plastic at night.
#include <string.h>

#include "theme.h"

namespace eyes {
namespace {

constexpr Rgb kBlack{0, 0, 0};

const ThemeSpec kThemes[] = {
    {
        .id = "human",
        .name = "Human",
        .sclera = {0.94f, 0.91f, 0.88f},
        .scleraEdge = {0.78f, 0.62f, 0.60f},
        .veins = 0.22f,
        .rings = 0,
        .irisRadius = 56,
        .irisInner = {0.62f, 0.45f, 0.16f},
        .irisOuter = {0.20f, 0.42f, 0.38f},
        .limbus = {0.06f, 0.07f, 0.06f},
        .limbusWidth = 7,
        .striation = 0.7f,
        .striationFreq = 70,
        .irisSwirl = 0,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.01f, 0.01f, 0.01f},
        .pupilMin = 14,
        .pupilMax = 32,
        .slitHeight = 0,
        .fire = FireMode::None,
        .fireLow = kBlack, .fireMid = kBlack, .fireHigh = kBlack,
        .fireScale = 0, .fireSpeed = 0, .fireAmount = 0, .fireInner = 0, .fireOuter = 0,
        .glowColor = kBlack, .glowRadius = 1, .glowAmount = 0, .glowPulse = 0,
        .specular = 0.9f,
        .scanlines = 0,
        .lids = true,
        .lidColor = {0.72f, 0.52f, 0.42f},
        .lidEdge = {0.35f, 0.18f, 0.15f},
        .gazeRange = 46,
        .saccadeRate = 0.7f,
        .blinkRate = 14,
        .jitter = 0.8f,
        .snap = false,
        .category = "classic",
    },
    {
        .id = "cat",
        .name = "Cat",
        .sclera = {0.30f, 0.26f, 0.05f},
        .scleraEdge = {0.08f, 0.06f, 0.02f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 104,
        .irisInner = {1.00f, 0.86f, 0.18f},
        .irisOuter = {0.42f, 0.62f, 0.08f},
        .limbus = {0.10f, 0.12f, 0.02f},
        .limbusWidth = 10,
        .striation = 0.45f,
        .striationFreq = 110,
        .irisSwirl = 0,
        .pupilShape = PupilShape::Slit,
        .pupilColor = {0.0f, 0.0f, 0.0f},
        .pupilMin = 5,
        .pupilMax = 46,
        .slitHeight = 0.92f,
        .fire = FireMode::None,
        .fireLow = kBlack, .fireMid = kBlack, .fireHigh = kBlack,
        .fireScale = 0, .fireSpeed = 0, .fireAmount = 0, .fireInner = 0, .fireOuter = 0,
        .glowColor = kBlack, .glowRadius = 1, .glowAmount = 0, .glowPulse = 0,
        .specular = 1.0f,
        .scanlines = 0,
        .lids = true,
        .lidColor = {0.20f, 0.17f, 0.14f},
        .lidEdge = {0.03f, 0.03f, 0.03f},
        .gazeRange = 16,
        .saccadeRate = 1.1f,
        .blinkRate = 5,
        .jitter = 0.5f,
        .snap = false,
        .category = "creatures",
        .blinkSpeed = 0.55f,  // the slow, trusting cat blink
        .pupilDilate = 1.3f,  // slits flood wide when startled
    },
    {
        .id = "fire",
        .name = "Fire",
        // Hollow sockets full of flames: no iris, no pupil, no lids.
        .sclera = {0.0f, 0.0f, 0.0f},
        .scleraEdge = {0.0f, 0.0f, 0.0f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 0,
        .pupilShape = PupilShape::None,
        .fire = FireMode::Pit,
        .fireLow = {0.60f, 0.04f, 0.0f},
        .fireMid = {1.0f, 0.40f, 0.02f},
        .fireHigh = {1.0f, 0.93f, 0.50f},
        .fireScale = 0.05f,
        .fireSpeed = 3.4f,
        .fireAmount = 1.0f,
        .fireInner = 0,
        .fireOuter = 140,
        .glowColor = {1.0f, 0.30f, 0.0f},
        .glowRadius = 70,
        .glowAmount = 0.45f,
        .glowPulse = 1.3f,
        .specular = 0,
        .scanlines = 0,
        .lids = false,
        .gazeRange = 12,
        .saccadeRate = 0.5f,
        .blinkRate = 4,
        .jitter = 0,
        .snap = false,
        .category = "halloween",
    },
    {
        .id = "alien",
        .name = "Alien",
        .sclera = {0.02f, 0.03f, 0.04f},
        .scleraEdge = {0.0f, 0.0f, 0.0f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 108,
        .irisInner = {0.02f, 0.30f, 0.28f},
        .irisOuter = {0.30f, 0.04f, 0.40f},
        .limbus = {0.01f, 0.01f, 0.02f},
        .limbusWidth = 14,
        .striation = 1.0f,
        .striationFreq = 14,
        .irisSwirl = 0.35f,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.0f, 0.0f, 0.0f},
        .pupilMin = 42,
        .pupilMax = 70,
        .slitHeight = 0,
        .fire = FireMode::None,
        .fireLow = kBlack, .fireMid = kBlack, .fireHigh = kBlack,
        .fireScale = 0, .fireSpeed = 0, .fireAmount = 0, .fireInner = 0, .fireOuter = 0,
        .glowColor = {0.1f, 0.9f, 0.6f},
        .glowRadius = 95,
        .glowAmount = 0.22f,  // faint teal bioluminescence so it reads at night
        .glowPulse = 0.15f,
        .specular = 0.7f,
        .scanlines = 0,
        .lids = true,
        .lidColor = {0.34f, 0.44f, 0.36f},
        .lidEdge = {0.12f, 0.18f, 0.14f},
        .gazeRange = 18,
        .saccadeRate = 1.6f,
        .blinkRate = 3,
        .jitter = 1.5f,
        .snap = false,
        .category = "sci-fi",
        .independence = 0.35f,  // eyes don't quite agree with each other
    },
    {
        .id = "sauron",
        .name = "Sauron",
        .sclera = {0.0f, 0.0f, 0.0f},
        .scleraEdge = {0.0f, 0.0f, 0.0f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 96,
        .irisInner = {1.00f, 0.72f, 0.18f},
        .irisOuter = {0.70f, 0.10f, 0.0f},
        .limbus = {0.25f, 0.02f, 0.0f},
        .limbusWidth = 20,
        .striation = 0.8f,
        .striationFreq = 60,
        .irisSwirl = 0.25f,
        .pupilShape = PupilShape::Slit,
        .pupilColor = {0.0f, 0.0f, 0.0f},
        .pupilMin = 5,
        .pupilMax = 14,
        .slitHeight = 0.95f,
        .fire = FireMode::Radial,
        .fireLow = {0.60f, 0.04f, 0.0f},
        .fireMid = {0.95f, 0.30f, 0.02f},
        .fireHigh = {1.0f, 0.80f, 0.35f},
        .fireScale = 1.6f,
        .fireSpeed = 1.6f,
        .fireAmount = 1.0f,
        .fireInner = 60,
        .fireOuter = 130,
        .glowColor = {1.0f, 0.5f, 0.1f},
        .glowRadius = 28,
        .glowAmount = 0.8f,
        .glowPulse = 0.35f,
        .specular = 0,
        .scanlines = 0,
        .lids = false,
        .lidColor = kBlack,
        .lidEdge = kBlack,
        .gazeRange = 14,
        .saccadeRate = 0.25f,
        .blinkRate = 0,
        .jitter = 0.4f,
        .snap = false,
        .category = "halloween",
        .scanRate = 3,  // the slow searching sweep
    },
    {
        .id = "terminator",
        .name = "Terminator",
        .sclera = {0.20f, 0.20f, 0.22f},
        .scleraEdge = {0.06f, 0.06f, 0.07f},
        .veins = 0,
        .rings = 1.0f,
        .irisRadius = 58,
        .irisInner = {1.0f, 0.12f, 0.03f},
        .irisOuter = {0.22f, 0.0f, 0.0f},
        .limbus = {0.03f, 0.03f, 0.03f},
        .limbusWidth = 8,
        .striation = 0,
        .striationFreq = 0,
        .irisSwirl = 0,
        .pupilShape = PupilShape::None,
        .pupilColor = kBlack,
        .pupilMin = 0,
        .pupilMax = 0,
        .slitHeight = 0,
        .fire = FireMode::None,
        .fireLow = kBlack, .fireMid = kBlack, .fireHigh = kBlack,
        .fireScale = 0, .fireSpeed = 0, .fireAmount = 0, .fireInner = 0, .fireOuter = 0,
        .glowColor = {1.0f, 0.05f, 0.0f},
        .glowRadius = 42,
        .glowAmount = 1.5f,
        .glowPulse = 0.5f,
        .specular = 0.35f,
        .scanlines = 0.5f,
        .lids = false,
        .lidColor = kBlack,
        .lidEdge = kBlack,
        .gazeRange = 30,
        .saccadeRate = 0.45f,
        .blinkRate = 4,
        .jitter = 0,
        .snap = true,
        .category = "sci-fi",
        .scanRate = 2,  // target acquisition sweep
    },
    {
        .id = "dragon",
        .name = "Dragon",
        .sclera = {0.25f, 0.06f, 0.02f},
        .scleraEdge = {0.05f, 0.01f, 0.00f},
        .irisRadius = 100,
        .irisInner = {1.00f, 0.80f, 0.10f},
        .irisOuter = {0.80f, 0.25f, 0.00f},
        .limbus = {0.20f, 0.05f, 0.00f},
        .limbusWidth = 10,
        .striation = 0.75f,
        .striationFreq = 80,
        .pupilShape = PupilShape::Slit,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 4,
        .pupilMax = 30,
        .slitHeight = 0.95f,
        .glowColor = {1.00f, 0.45f, 0.05f},
        .glowRadius = 60,
        .glowAmount = 0.2f,
        .glowPulse = 0.15f,
        .specular = 0.8f,
        .lids = true,
        .lidColor = {0.18f, 0.30f, 0.12f},
        .lidEdge = {0.05f, 0.10f, 0.03f},
        .gazeRange = 16,
        .saccadeRate = 0.5f,
        .blinkRate = 4,
        .jitter = 0.3f,
        .snap = false,
        .category = "creatures",
        .blinkSpeed = 0.7f,
        .pupilDilate = 1.3f,
    },
    {
        .id = "zombie",
        .name = "Zombie",
        // Left eye still tracks; the right one is a milky, wall-eyed cataract.
        .sclera = {0.78f, 0.80f, 0.68f},
        .scleraEdge = {0.45f, 0.40f, 0.25f},
        .veins = 0.7f,
        .irisRadius = 52,
        .irisInner = {0.75f, 0.78f, 0.72f},
        .irisOuter = {0.55f, 0.60f, 0.58f},
        .limbus = {0.40f, 0.42f, 0.40f},
        .limbusWidth = 5,
        .striation = 0.3f,
        .striationFreq = 40,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.36f, 0.40f, 0.36f},
        .pupilMin = 8,
        .pupilMax = 14,
        .glowRadius = 1,
        .specular = 0.3f,
        .lids = true,
        .lidColor = {0.45f, 0.50f, 0.38f},
        .lidEdge = {0.40f, 0.10f, 0.10f},
        .gazeRange = 38,
        .saccadeRate = 0.3f,
        .blinkRate = 3,
        .jitter = 2.5f,
        .snap = false,
        .category = "halloween",
        .lidDroop = 0.12f,
        .blinkSpeed = 0.6f,
        .right = {.enabled = true,
                  .irisInner = {0.82f, 0.84f, 0.78f},
                  .irisOuter = {0.60f, 0.64f, 0.58f},
                  .pupilColor = {0.50f, 0.52f, 0.48f},
                  .glowColor = kBlack,
                  .pupilScale = 0.6f,
                  .glowScale = 0,
                  .haze = 0.7f,
                  .lazy = 0.8f},
    },
    {
        .id = "demon",
        .name = "Demon",
        .sclera = {0.06f, 0.00f, 0.00f},
        .scleraEdge = {0.00f, 0.00f, 0.00f},
        .irisRadius = 90,
        .irisInner = {1.00f, 0.60f, 0.05f},
        .irisOuter = {0.70f, 0.03f, 0.00f},
        .limbus = {0.10f, 0.00f, 0.00f},
        .limbusWidth = 12,
        .striation = 0.6f,
        .striationFreq = 50,
        .irisSwirl = 0.1f,
        .pupilShape = PupilShape::Bar,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 7,
        .pupilMax = 16,
        .slitHeight = 0.55f,
        .fire = FireMode::Rising,
        .fireLow = {0.50f, 0.00f, 0.00f},
        .fireMid = {0.95f, 0.15f, 0.00f},
        .fireHigh = {1.00f, 0.60f, 0.20f},
        .fireScale = 0.05f,
        .fireSpeed = 3.5f,
        .fireAmount = 0.8f,
        .fireInner = 86,
        .fireOuter = 125,
        .glowColor = {1.00f, 0.10f, 0.00f},
        .glowRadius = 70,
        .glowAmount = 0.2f,
        .specular = 0.3f,
        .lids = true,
        .lidColor = {0.08f, 0.02f, 0.02f},
        .lidEdge = {0.90f, 0.10f, 0.00f},
        .gazeRange = 14,
        .saccadeRate = 0.4f,
        .blinkRate = 2,
        .jitter = 0.3f,
        .snap = false,
        .category = "halloween",
    },
    {
        .id = "werewolf",
        .name = "Werewolf",
        .sclera = {0.35f, 0.25f, 0.08f},
        .scleraEdge = {0.08f, 0.05f, 0.02f},
        .irisRadius = 88,
        .irisInner = {1.00f, 0.85f, 0.35f},
        .irisOuter = {0.80f, 0.45f, 0.05f},
        .limbus = {0.15f, 0.08f, 0.02f},
        .limbusWidth = 10,
        .striation = 0.8f,
        .striationFreq = 90,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 10,
        .pupilMax = 34,
        .glowColor = {1.00f, 0.60f, 0.10f},
        .glowRadius = 80,
        .glowAmount = 0.15f,  // eyeshine
        .specular = 0.9f,
        .lids = true,
        .lidColor = {0.25f, 0.20f, 0.16f},
        .lidEdge = {0.05f, 0.04f, 0.03f},
        .gazeRange = 20,
        .saccadeRate = 1.3f,
        .blinkRate = 6,
        .jitter = 0.8f,
        .snap = false,
        .category = "halloween",
        .pupilDilate = 1.2f,
    },
    {
        .id = "vampire",
        .name = "Vampire",
        .sclera = {0.93f, 0.88f, 0.88f},
        .scleraEdge = {0.70f, 0.55f, 0.60f},
        .veins = 0.35f,
        .irisRadius = 54,
        .irisInner = {1.00f, 0.10f, 0.12f},
        .irisOuter = {0.35f, 0.00f, 0.02f},
        .limbus = {0.10f, 0.00f, 0.00f},
        .limbusWidth = 7,
        .striation = 0.7f,
        .striationFreq = 70,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.02f, 0.00f, 0.00f},
        .pupilMin = 10,
        .pupilMax = 24,
        .glowColor = {1.00f, 0.00f, 0.05f},
        .glowRadius = 48,
        .glowAmount = 0.4f,
        .glowPulse = 0.2f,
        .specular = 0.9f,
        .lids = true,
        .lidColor = {0.85f, 0.78f, 0.78f},
        .lidEdge = {0.35f, 0.10f, 0.15f},
        .gazeRange = 40,
        .saccadeRate = 0.5f,
        .blinkRate = 6,
        .jitter = 0.4f,
        .snap = false,
        .category = "halloween",
        .lidDroop = 0.08f,
        .blinkSpeed = 0.8f,
    },
    {
        .id = "ghost",
        .name = "Ghost",
        // A cold, luminous ring with ectoplasm drifting off it; hollow black centre.
        .sclera = {0.00f, 0.00f, 0.00f},
        .scleraEdge = {0.00f, 0.00f, 0.00f},
        .irisRadius = 76,
        .irisInner = {0.95f, 1.00f, 1.00f},
        .irisOuter = {0.40f, 0.65f, 0.90f},
        .limbus = {0.15f, 0.30f, 0.50f},
        .limbusWidth = 12,
        .striation = 0.3f,
        .striationFreq = 20,
        .irisSwirl = 0.4f,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 30,
        .pupilMax = 52,
        .fire = FireMode::Radial,
        .fireLow = {0.05f, 0.12f, 0.22f},
        .fireMid = {0.30f, 0.55f, 0.80f},
        .fireHigh = {0.80f, 0.95f, 1.00f},
        .fireScale = 1.1f,
        .fireSpeed = 0.55f,
        .fireAmount = 0.9f,
        .fireInner = 70,
        .fireOuter = 128,
        .glowColor = {0.55f, 0.80f, 1.00f},
        .glowRadius = 105,
        .glowAmount = 0.5f,
        .glowPulse = 0.25f,
        .lids = false,
        .gazeRange = 22,
        .saccadeRate = 0.3f,
        .blinkRate = 3,
        .jitter = 0,
        .snap = false,
        .category = "halloween",
        .scanRate = 1.5f,
    },
    {
        .id = "jack_o_lantern",
        .name = "Jack-o'-Lantern",
        .sclera = {0.00f, 0.00f, 0.00f},
        .scleraEdge = {0.00f, 0.00f, 0.00f},
        .irisRadius = 0,
        .pupilShape = PupilShape::Triangle,
        .pupilColor = {0.02f, 0.01f, 0.0f},
        .pupilMin = 86,
        .pupilMax = 94,
        .fire = FireMode::Rising,
        .fireLow = {0.75f, 0.15f, 0.00f},
        .fireMid = {1.00f, 0.55f, 0.04f},
        .fireHigh = {1.00f, 0.92f, 0.45f},
        .fireScale = 0.035f,
        .fireSpeed = 2.6f,
        .fireAmount = 1.0f,
        .fireInner = 0,
        .fireOuter = 150,
        .glowColor = {1.00f, 0.45f, 0.05f},
        .glowRadius = 80,
        .glowAmount = 1.1f,
        .glowPulse = 1.8f,
        .lids = false,
        .gazeRange = 8,
        .saccadeRate = 0.2f,
        .blinkRate = 5,
        .jitter = 0,
        .snap = false,
        .pupilInvert = true,
        .category = "halloween",
    },
    {
        .id = "hypnotic",
        .name = "Hypnotic",
        .sclera = {0.00f, 0.00f, 0.00f},
        .scleraEdge = {0.00f, 0.00f, 0.00f},
        .irisRadius = 114,
        .irisInner = {1.00f, 1.00f, 1.00f},
        .irisOuter = {0.35f, 0.00f, 0.55f},
        .limbus = {0.05f, 0.00f, 0.08f},
        .limbusWidth = 6,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 6,
        .pupilMax = 14,
        .glowRadius = 1,
        .lids = false,
        .gazeRange = 0,
        .saccadeRate = 0,
        .blinkRate = 0,
        .jitter = 0,
        .snap = false,
        .spiral = 1.0f,
        .spiralSpeed = 5.0f,
        .category = "fun",
    },
    {
        .id = "owl",
        .name = "Owl",
        .sclera = {0.25f, 0.20f, 0.12f},
        .scleraEdge = {0.10f, 0.08f, 0.05f},
        .irisRadius = 96,
        .irisInner = {1.00f, 0.60f, 0.05f},
        .irisOuter = {1.00f, 0.80f, 0.15f},
        .limbus = {0.30f, 0.12f, 0.00f},
        .limbusWidth = 6,
        .striation = 0.4f,
        .striationFreq = 100,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 30,
        .pupilMax = 70,
        .glowRadius = 1,
        .specular = 1.0f,
        .lids = true,
        .lidColor = {0.45f, 0.35f, 0.25f},
        .lidEdge = {0.20f, 0.15f, 0.10f},
        .gazeRange = 10,
        .saccadeRate = 0.4f,
        .blinkRate = 4,
        .jitter = 0,
        .snap = true,  // owls turn their heads; the eyes themselves lock on
        .category = "creatures",
        .blinkSpeed = 0.7f,
    },
    {
        .id = "frost",
        .name = "Frost",
        .sclera = {0.85f, 0.93f, 1.00f},
        .scleraEdge = {0.50f, 0.65f, 0.85f},
        .irisRadius = 58,
        .irisInner = {0.90f, 0.98f, 1.00f},
        .irisOuter = {0.20f, 0.55f, 0.95f},
        .limbus = {0.05f, 0.15f, 0.35f},
        .limbusWidth = 7,
        .striation = 0.9f,
        .striationFreq = 36,
        .irisSwirl = 0.05f,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.02f, 0.04f, 0.10f},
        .pupilMin = 12,
        .pupilMax = 26,
        .glowColor = {0.60f, 0.85f, 1.00f},
        .glowRadius = 50,
        .glowAmount = 0.2f,
        .specular = 1.0f,
        .lids = true,
        .lidColor = {0.70f, 0.80f, 0.90f},
        .lidEdge = {0.95f, 0.98f, 1.00f},
        .gazeRange = 42,
        .saccadeRate = 0.6f,
        .blinkRate = 10,
        .jitter = 0.5f,
        .snap = false,
        .category = "holidays",
        .sparkle = 0.6f,  // ice glints
    },
    {
        .id = "valentine",
        .name = "Valentine",
        .sclera = {1.00f, 0.93f, 0.95f},
        .scleraEdge = {0.90f, 0.70f, 0.80f},
        .irisRadius = 64,
        .irisInner = {1.00f, 0.40f, 0.60f},
        .irisOuter = {0.80f, 0.05f, 0.30f},
        .limbus = {0.35f, 0.00f, 0.10f},
        .limbusWidth = 6,
        .striation = 0.4f,
        .striationFreq = 50,
        .pupilShape = PupilShape::Heart,
        .pupilColor = {0.25f, 0.00f, 0.05f},
        .pupilMin = 22,
        .pupilMax = 34,
        .glowColor = {1.00f, 0.30f, 0.60f},
        .glowRadius = 60,
        .glowAmount = 0.25f,
        .glowPulse = 1.2f,
        .specular = 1.0f,
        .lids = true,
        .lidColor = {0.95f, 0.75f, 0.72f},
        .lidEdge = {0.50f, 0.20f, 0.25f},
        .gazeRange = 40,
        .saccadeRate = 0.6f,
        .blinkRate = 14,
        .jitter = 0.4f,
        .snap = false,
        .category = "holidays",
        .sparkle = 0.5f,
    },
    {
        .id = "rainbow",
        .name = "Rainbow",
        .sclera = {0.97f, 0.97f, 0.97f},
        .scleraEdge = {0.75f, 0.75f, 0.80f},
        .irisRadius = 70,
        .irisInner = {1.00f, 0.20f, 0.20f},
        .irisOuter = {0.20f, 0.40f, 1.00f},
        .limbus = {0.10f, 0.05f, 0.15f},
        .limbusWidth = 6,
        .striation = 0.6f,
        .striationFreq = 24,
        .irisSwirl = 0.8f,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 16,
        .pupilMax = 30,
        .glowRadius = 1,
        .specular = 1.0f,
        .lids = true,
        .lidColor = {0.40f, 0.25f, 0.60f},
        .lidEdge = {1.00f, 0.80f, 0.20f},
        .gazeRange = 36,
        .saccadeRate = 1.2f,
        .blinkRate = 12,
        .jitter = 0.4f,
        .snap = false,
        .hueSpin = 0.25f,
        .category = "fun",
    },
    {
        .id = "robot",
        .name = "Robot",
        .sclera = {0.20f, 0.22f, 0.25f},
        .scleraEdge = {0.06f, 0.06f, 0.08f},
        .rings = 1.0f,
        .irisRadius = 66,
        .irisInner = {0.30f, 0.90f, 1.00f},
        .irisOuter = {0.00f, 0.15f, 0.35f},
        .limbus = {0.03f, 0.03f, 0.04f},
        .limbusWidth = 8,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.00f, 0.02f, 0.05f},
        .pupilMin = 14,
        .pupilMax = 30,
        .glowColor = {0.20f, 0.70f, 1.00f},
        .glowRadius = 44,
        .glowAmount = 0.7f,
        .glowPulse = 0.3f,
        .specular = 0.35f,
        .scanlines = 0.35f,
        .lids = false,
        .gazeRange = 32,
        .saccadeRate = 0.7f,
        .blinkRate = 3,
        .jitter = 0,
        .snap = true,
        .category = "sci-fi",
        .scanRate = 1.5f,
    },

    // ------------------------------------------------------------------ v1.2 additions
    {
        .id = "snake",
        .name = "Snake",
        // Lidless, never blinks: copper-gold iris filling the socket, hairline slit that
        // floods wide when startled. Dead still, then a quick strike of a glance.
        .sclera = {0.20f, 0.12f, 0.02f},
        .scleraEdge = {0.05f, 0.03f, 0.00f},
        .irisRadius = 116,
        .irisInner = {0.95f, 0.68f, 0.18f},
        .irisOuter = {0.38f, 0.24f, 0.03f},
        .limbus = {0.08f, 0.05f, 0.00f},
        .limbusWidth = 22,
        .striation = 1.0f,
        .striationFreq = 150,
        .irisSwirl = 0,
        .pupilShape = PupilShape::Slit,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 3,
        .pupilMax = 40,
        .slitHeight = 0.9f,
        .glowColor = {1.00f, 0.70f, 0.20f},
        .glowRadius = 60,
        .glowAmount = 0.12f,
        .specular = 0.55f,
        .lids = false,
        .gazeRange = 14,
        .saccadeRate = 0.3f,
        .blinkRate = 0,
        .jitter = 0.2f,
        .snap = false,
        .category = "creatures",
        .pupilDilate = 1.5f,
    },
    {
        .id = "spider",
        .name = "Spider",
        // Four glossy black orbs per panel (eight in all): one big forward eye and three
        // small ones above it, each with a wet highlight. Lidless; never blinks.
        .sclera = {0.03f, 0.02f, 0.02f},
        .scleraEdge = {0.00f, 0.00f, 0.00f},
        .irisRadius = 64,
        .irisInner = {0.60f, 0.08f, 0.04f},
        .irisOuter = {0.16f, 0.02f, 0.01f},
        .limbus = {0.02f, 0.00f, 0.00f},
        .limbusWidth = 8,
        .striation = 0.35f,
        .striationFreq = 40,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 20,
        .pupilMax = 36,
        .glowColor = {1.00f, 0.15f, 0.05f},
        .glowRadius = 50,
        .glowAmount = 0.45f,
        .glowPulse = 0.6f,
        .specular = 1.0f,
        .lids = false,
        .gazeRange = 8,
        .saccadeRate = 1.0f,
        .blinkRate = 0,
        .jitter = 0.6f,
        .snap = true,
        .category = "halloween",
        .cluster = 4,
    },
    {
        .id = "chameleon",
        .name = "Chameleon",
        // Scaly green turrets: each eye swivels on its own, then both lock on when commanded.
        .sclera = {0.35f, 0.55f, 0.12f},
        .scleraEdge = {0.08f, 0.15f, 0.03f},
        .veins = 0,
        .rings = 0.6f,
        .irisRadius = 34,
        .irisInner = {1.00f, 0.80f, 0.25f},
        .irisOuter = {0.75f, 0.40f, 0.05f},
        .limbus = {0.10f, 0.08f, 0.02f},
        .limbusWidth = 5,
        .striation = 0.5f,
        .striationFreq = 60,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 8,
        .pupilMax = 16,
        .glowRadius = 1,
        .specular = 0.9f,
        .lids = false,
        .gazeRange = 62,
        .saccadeRate = 0.6f,
        .blinkRate = 0,
        .jitter = 0.3f,
        .snap = false,
        .category = "creatures",
        .independence = 1.0f,
    },
    {
        .id = "puppy",
        .name = "Sleepy Puppy",
        // Big wet brown eyes with heavy lids that keep sagging shut, then jolting open.
        .sclera = {0.92f, 0.88f, 0.80f},
        .scleraEdge = {0.55f, 0.42f, 0.30f},
        .veins = 0.05f,
        .irisRadius = 90,
        .irisInner = {0.60f, 0.35f, 0.12f},
        .irisOuter = {0.28f, 0.14f, 0.05f},
        .limbus = {0.08f, 0.04f, 0.02f},
        .limbusWidth = 8,
        .striation = 0.35f,
        .striationFreq = 60,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.02f, 0.01f, 0.01f},
        .pupilMin = 36,
        .pupilMax = 56,
        .glowRadius = 1,
        .specular = 1.0f,
        .lids = true,
        .lidColor = {0.45f, 0.30f, 0.20f},
        .lidEdge = {0.15f, 0.08f, 0.05f},
        .gazeRange = 20,
        .saccadeRate = 0.25f,
        .blinkRate = 6,
        .jitter = 0.3f,
        .snap = false,
        .category = "fun",
        .sparkle = 0.35f,
        .lidDroop = 0.22f,
        .blinkSpeed = 0.45f,
        .dozeRate = 4,
    },
    {
        .id = "anime",
        .name = "Anime",
        // Huge glossy iris, deep rim, twinkling star highlights and thick dark lashes.
        .sclera = {1.00f, 1.00f, 1.00f},
        .scleraEdge = {0.80f, 0.85f, 0.95f},
        .irisRadius = 100,
        .irisInner = {0.55f, 0.95f, 1.00f},
        .irisOuter = {0.05f, 0.25f, 0.75f},
        .limbus = {0.02f, 0.05f, 0.25f},
        .limbusWidth = 18,
        .striation = 0.35f,
        .striationFreq = 40,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.02f, 0.05f, 0.20f},
        .pupilMin = 30,
        .pupilMax = 44,
        .glowColor = {0.60f, 0.90f, 1.00f},
        .glowRadius = 70,
        .glowAmount = 0.15f,
        .specular = 1.0f,
        .lids = true,
        .lidColor = {0.12f, 0.08f, 0.14f},
        .lidEdge = {0.02f, 0.01f, 0.03f},
        .gazeRange = 24,
        .saccadeRate = 0.8f,
        .blinkRate = 10,
        .jitter = 0.3f,
        .snap = false,
        .category = "fun",
        .sparkle = 1.0f,
        .blinkSpeed = 0.8f,
    },
    {
        .id = "st_patricks",
        .name = "St. Patrick's",
        .sclera = {0.96f, 0.95f, 0.88f},
        .scleraEdge = {0.70f, 0.72f, 0.55f},
        .irisRadius = 70,
        .irisInner = {0.55f, 0.95f, 0.30f},
        .irisOuter = {0.02f, 0.40f, 0.10f},
        .limbus = {0.85f, 0.65f, 0.10f},  // gold rim
        .limbusWidth = 8,
        .striation = 0.5f,
        .striationFreq = 60,
        .pupilShape = PupilShape::Clover,
        .pupilColor = {0.01f, 0.08f, 0.02f},
        .pupilMin = 24,
        .pupilMax = 34,
        .glowColor = {1.00f, 0.80f, 0.20f},
        .glowRadius = 70,
        .glowAmount = 0.2f,
        .glowPulse = 0.5f,
        .specular = 1.0f,
        .lids = true,
        .lidColor = {0.15f, 0.45f, 0.18f},
        .lidEdge = {0.90f, 0.70f, 0.15f},
        .gazeRange = 40,
        .saccadeRate = 0.9f,
        .blinkRate = 12,
        .jitter = 0.5f,
        .snap = false,
        .category = "holidays",
        .sparkle = 0.3f,
    },
    {
        .id = "easter",
        .name = "Easter",
        // Pastel: a lavender-to-mint iris that slowly cycles through candy colours.
        .sclera = {1.00f, 0.98f, 0.94f},
        .scleraEdge = {0.90f, 0.80f, 0.85f},
        .irisRadius = 74,
        .irisInner = {0.90f, 0.62f, 1.00f},
        .irisOuter = {0.30f, 0.80f, 0.62f},
        .limbus = {0.40f, 0.25f, 0.60f},
        .limbusWidth = 7,
        .striation = 0.5f,
        .striationFreq = 30,
        .irisSwirl = 0.3f,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.15f, 0.05f, 0.20f},
        .pupilMin = 16,
        .pupilMax = 30,
        .glowColor = {1.00f, 0.85f, 0.95f},
        .glowRadius = 60,
        .glowAmount = 0.15f,
        .specular = 1.0f,
        .lids = true,
        .lidColor = {0.98f, 0.78f, 0.85f},
        .lidEdge = {0.75f, 0.45f, 0.65f},
        .gazeRange = 36,
        .saccadeRate = 0.8f,
        .blinkRate = 12,
        .jitter = 0.4f,
        .snap = false,
        .hueSpin = 0.04f,
        .category = "holidays",
        .sparkle = 0.5f,
    },
    {
        .id = "fireworks",
        .name = "Fireworks",
        // Night-sky socket: a white-hot core with a star cut into it and red/white/blue
        // sparks bursting outward.
        .sclera = {0.00f, 0.00f, 0.03f},
        .scleraEdge = {0.00f, 0.00f, 0.00f},
        .irisRadius = 44,
        .irisInner = {1.00f, 1.00f, 0.92f},
        .irisOuter = {1.00f, 0.80f, 0.40f},
        .limbus = {0.90f, 0.35f, 0.05f},
        .limbusWidth = 6,
        .pupilShape = PupilShape::Star,
        .pupilColor = {0.85f, 0.05f, 0.08f},
        .pupilMin = 26,
        .pupilMax = 34,
        .fire = FireMode::Radial,
        .fireLow = {0.12f, 0.00f, 0.04f},  // near black so only the bright streaks show
        .fireMid = {1.00f, 0.25f, 0.20f},
        .fireHigh = {0.85f, 0.95f, 1.00f},
        .fireScale = 1.8f,
        .fireSpeed = 6.0f,
        .fireAmount = 1.0f,
        .fireInner = 48,
        .fireOuter = 128,
        .glowColor = {1.00f, 0.90f, 0.70f},
        .glowRadius = 60,
        .glowAmount = 0.8f,
        .glowPulse = 0.7f,
        .lids = false,
        .gazeRange = 20,
        .saccadeRate = 0.5f,
        .blinkRate = 6,
        .jitter = 0,
        .snap = false,
        .category = "holidays",
        .fireStretch = 0.18f,  // long radial sparks racing outward
    },
    {
        .id = "dead",
        .name = "Dead (X_X)",
        // Cartoon dead eyes: bone-white with a big black X, a sickly green glow, never moves.
        .sclera = {0.90f, 0.95f, 0.82f},
        .scleraEdge = {0.35f, 0.45f, 0.30f},
        .veins = 0.25f,
        .irisRadius = 0,
        .pupilShape = PupilShape::Cross,
        .pupilColor = {0.02f, 0.02f, 0.02f},
        .pupilMin = 48,
        .pupilMax = 54,
        .slitHeight = 0.2f,  // X stroke thickness
        .glowColor = {0.40f, 1.00f, 0.30f},
        .glowRadius = 90,
        .glowAmount = 0.18f,
        .glowPulse = 0.4f,
        .lids = true,
        .lidColor = {0.55f, 0.62f, 0.48f},
        .lidEdge = {0.30f, 0.10f, 0.12f},
        .gazeRange = 4,
        .saccadeRate = 0.05f,
        .blinkRate = 1,
        .jitter = 0,
        .snap = false,
        .category = "halloween",
        .lidDroop = 0.15f,
        .blinkSpeed = 0.4f,
    },

    // ------------------------------------------------------------------ v1.3 additions
    {
        .id = "chucky",
        .name = "Killer Doll",
        // A toy-store doll's eyes: glassy, too-blue, too-perfect vinyl with painted lashes and
        // a hard glint. Dead still and unblinking, then a sudden snap of the eyes.
        .sclera = {0.99f, 0.99f, 0.97f},
        .scleraEdge = {0.82f, 0.84f, 0.90f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 70,
        .irisInner = {0.62f, 0.90f, 1.00f},
        .irisOuter = {0.04f, 0.20f, 0.72f},
        .limbus = {0.02f, 0.03f, 0.16f},
        .limbusWidth = 8,
        .striation = 0.3f,
        .striationFreq = 48,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.00f, 0.00f, 0.02f},
        .pupilMin = 17,
        .pupilMax = 26,
        .glowColor = {0.40f, 0.70f, 1.00f},
        .glowRadius = 72,
        .glowAmount = 0.12f,
        .specular = 1.0f,
        .lids = true,
        .lidColor = {0.93f, 0.72f, 0.62f},  // vinyl skin
        .lidEdge = {0.20f, 0.09f, 0.06f},   // painted lashes
        .gazeRange = 34,
        .saccadeRate = 0.3f,
        .blinkRate = 1.5f,
        .jitter = 0,
        .snap = true,  // doll eyes click into place
        .category = "halloween",
        .sparkle = 0.3f,     // the sinister glint
        .blinkSpeed = 2.0f,  // when it finally blinks, it's a snap
        .pupilDilate = 0.5f, // plastic pupils barely react
    },
    {
        .id = "saw",
        .name = "Puppet",
        // Ventriloquist-dummy face: a white ceramic eyeball with a painted red spiral slowly
        // creeping round a hollow black socket; inside, a small glowing red eye with a
        // pinpoint glint. No lids, never blinks, head-jerk snaps.
        .sclera = {0.96f, 0.94f, 0.88f},
        .scleraEdge = {0.88f, 0.84f, 0.76f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 40,
        .irisInner = {1.00f, 0.16f, 0.08f},
        .irisOuter = {0.74f, 0.02f, 0.00f},
        .limbus = {0.22f, 0.00f, 0.00f},
        .limbusWidth = 6,
        .striation = 0.3f,
        .striationFreq = 50,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 7,
        .pupilMax = 14,
        .glowColor = {1.00f, 0.08f, 0.02f},
        .glowRadius = 46,
        .glowAmount = 0.55f,
        .glowPulse = 0.3f,
        .specular = 0.9f,
        .lids = false,
        .gazeRange = 14,
        .saccadeRate = 0.35f,
        .blinkRate = 0,
        .jitter = 0,
        .snap = true,
        .category = "halloween",
        .socket = 14,
        .socketColor = {0.02f, 0.01f, 0.01f},
        .scleraSpiral = 1.0f,
        .scleraSpiralColor = {0.82f, 0.05f, 0.04f},
        .scleraSpiralX = -50,  // the painted cheek spiral sits low and outward of the socket
        .scleraSpiralY = 48,
        .scleraSpiralRadius = 44,
    },
    {
        .id = "blood_zombie",
        .name = "Bloodshot Zombie",
        // Both eyes alive and hunting: blood-red glowing irises that throb, bloodshot sclera
        // under heavy veins, blue-grey dead skin on the lids. Twitchy and menacing.
        .sclera = {0.86f, 0.70f, 0.64f},
        .scleraEdge = {0.40f, 0.06f, 0.05f},
        .veins = 1.0f,
        .rings = 0,
        .irisRadius = 64,
        .irisInner = {1.00f, 0.32f, 0.12f},
        .irisOuter = {0.62f, 0.00f, 0.00f},
        .limbus = {0.16f, 0.00f, 0.00f},
        .limbusWidth = 8,
        .striation = 0.7f,
        .striationFreq = 70,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.02f, 0.00f, 0.00f},
        .pupilMin = 10,
        .pupilMax = 22,
        .glowColor = {1.00f, 0.10f, 0.02f},
        .glowRadius = 58,
        .glowAmount = 0.6f,
        .glowPulse = 0.8f,
        .specular = 0.5f,
        .lids = true,
        .lidColor = {0.38f, 0.44f, 0.50f},  // blue-grey dead skin
        .lidEdge = {0.10f, 0.05f, 0.08f},   // sunken dark sockets
        .gazeRange = 36,
        .saccadeRate = 0.5f,
        .blinkRate = 2,
        .jitter = 2.0f,
        .snap = false,
        .category = "halloween",
        .lidDroop = 0.10f,
        .blinkSpeed = 0.7f,
        .pupilDilate = 1.3f,
    },
    {
        .id = "witch",
        .name = "Witch",
        // Wicked witch: a poison-green iris glowing out of a violet-black socket, a cat-like
        // slit that floods wide, green cauldron flames licking up around it and warty green
        // lids half-narrowed in a scheming squint. Slow sidelong glances, rare blinks.
        .sclera = {0.10f, 0.02f, 0.14f},
        .scleraEdge = {0.00f, 0.00f, 0.00f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 84,
        .irisInner = {0.58f, 0.96f, 0.22f},
        .irisOuter = {0.04f, 0.42f, 0.08f},
        .limbus = {0.02f, 0.10f, 0.03f},
        .limbusWidth = 12,
        .striation = 0.7f,
        .striationFreq = 80,
        .irisSwirl = 0.15f,  // the potion keeps stirring
        .pupilShape = PupilShape::Slit,
        .pupilColor = {0.00f, 0.00f, 0.00f},
        .pupilMin = 6,
        .pupilMax = 30,
        .slitHeight = 0.92f,
        .fire = FireMode::Rising,
        .fireLow = {0.16f, 0.02f, 0.22f},
        .fireMid = {0.25f, 0.80f, 0.10f},
        .fireHigh = {0.80f, 1.00f, 0.55f},
        .fireScale = 0.06f,
        .fireSpeed = 3.0f,
        .fireAmount = 0.8f,
        .fireInner = 80,
        .fireOuter = 126,
        .glowColor = {0.40f, 1.00f, 0.25f},
        .glowRadius = 95,
        .glowAmount = 0.22f,
        .glowPulse = 0.45f,
        .specular = 0.6f,
        .scanlines = 0,
        .lids = true,
        .lidColor = {0.26f, 0.42f, 0.14f},  // green witch skin
        .lidEdge = {0.04f, 0.08f, 0.02f},   // dark lash line
        .gazeRange = 30,
        .saccadeRate = 0.5f,
        .blinkRate = 4,
        .jitter = 0.4f,
        .snap = false,
        .category = "halloween",
        .lidDroop = 0.14f,   // the scheming squint
        .blinkSpeed = 0.8f,
        .pupilDilate = 1.4f,
    },
};

constexpr int kThemeCount = sizeof(kThemes) / sizeof(kThemes[0]);

// Cluster layouts (left panel; x is mirrored for the right panel).
const ClusterEye kCluster4[4] = {
    {0, 16, 1.0f},        // big anterior eye
    {-66, -56, 0.42f},    // small lateral eye
    {0, -84, 0.50f},      // small median eye
    {66, -56, 0.42f},
};
const ClusterEye kCluster5[5] = {
    {0, 22, 1.0f}, {-70, -40, 0.38f}, {-30, -82, 0.40f}, {30, -82, 0.40f}, {70, -40, 0.38f},
};

}  // namespace

const ClusterEye* clusterLayout(int count) { return count >= 5 ? kCluster5 : kCluster4; }

const ThemeSpec* themeById(const char* id) {
  for (const auto& t : kThemes)
    if (strcmp(t.id, id) == 0) return &t;
  return nullptr;
}

const ThemeSpec* themeAt(int index) {
  return (index >= 0 && index < kThemeCount) ? &kThemes[index] : nullptr;
}

int themeCount() { return kThemeCount; }

}  // namespace eyes
