// Built-in themes. Designated initialisers must follow ThemeSpec's field order.
#include <string.h>

#include "theme.h"

namespace eyes {
namespace {

constexpr Rgb kBlack{0, 0, 0};

const ThemeSpec kThemes[] = {
    {
        .id = "human",
        .name = "Human",
        .sclera = {0.94f, 0.91f, 0.88f},
        .scleraEdge = {0.78f, 0.62f, 0.60f},
        .veins = 0.22f,
        .rings = 0,
        .irisRadius = 56,
        .irisInner = {0.62f, 0.45f, 0.16f},
        .irisOuter = {0.20f, 0.42f, 0.38f},
        .limbus = {0.06f, 0.07f, 0.06f},
        .limbusWidth = 7,
        .striation = 0.7f,
        .striationFreq = 70,
        .irisSwirl = 0,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.01f, 0.01f, 0.01f},
        .pupilMin = 14,
        .pupilMax = 32,
        .slitHeight = 0,
        .fire = FireMode::None,
        .fireLow = kBlack, .fireMid = kBlack, .fireHigh = kBlack,
        .fireScale = 0, .fireSpeed = 0, .fireAmount = 0, .fireInner = 0, .fireOuter = 0,
        .glowColor = kBlack, .glowRadius = 1, .glowAmount = 0, .glowPulse = 0,
        .specular = 0.9f,
        .scanlines = 0,
        .lids = true,
        .lidColor = {0.72f, 0.52f, 0.42f},
        .lidEdge = {0.35f, 0.18f, 0.15f},
        .gazeRange = 46,
        .saccadeRate = 0.7f,
        .blinkRate = 14,
        .jitter = 0.8f,
        .snap = false,
    },
    {
        .id = "cat",
        .name = "Cat",
        .sclera = {0.30f, 0.26f, 0.05f},
        .scleraEdge = {0.08f, 0.06f, 0.02f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 104,
        .irisInner = {1.00f, 0.86f, 0.18f},
        .irisOuter = {0.42f, 0.62f, 0.08f},
        .limbus = {0.10f, 0.12f, 0.02f},
        .limbusWidth = 10,
        .striation = 0.45f,
        .striationFreq = 110,
        .irisSwirl = 0,
        .pupilShape = PupilShape::Slit,
        .pupilColor = {0.0f, 0.0f, 0.0f},
        .pupilMin = 5,
        .pupilMax = 46,
        .slitHeight = 0.92f,
        .fire = FireMode::None,
        .fireLow = kBlack, .fireMid = kBlack, .fireHigh = kBlack,
        .fireScale = 0, .fireSpeed = 0, .fireAmount = 0, .fireInner = 0, .fireOuter = 0,
        .glowColor = kBlack, .glowRadius = 1, .glowAmount = 0, .glowPulse = 0,
        .specular = 1.0f,
        .scanlines = 0,
        .lids = true,
        .lidColor = {0.20f, 0.17f, 0.14f},
        .lidEdge = {0.03f, 0.03f, 0.03f},
        .gazeRange = 16,
        .saccadeRate = 1.1f,
        .blinkRate = 5,
        .jitter = 0.5f,
        .snap = false,
    },
    {
        .id = "fire",
        .name = "Fire",
        .sclera = {0.05f, 0.01f, 0.0f},
        .scleraEdge = {0.0f, 0.0f, 0.0f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 62,
        .irisInner = {1.00f, 0.90f, 0.40f},
        .irisOuter = {0.85f, 0.18f, 0.0f},
        .limbus = {0.35f, 0.02f, 0.0f},
        .limbusWidth = 6,
        .striation = 0.6f,
        .striationFreq = 40,
        .irisSwirl = 0.6f,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.02f, 0.0f, 0.0f},
        .pupilMin = 12,
        .pupilMax = 26,
        .slitHeight = 0,
        .fire = FireMode::Rising,
        .fireLow = {0.55f, 0.03f, 0.0f},
        .fireMid = {1.0f, 0.38f, 0.02f},
        .fireHigh = {1.0f, 0.92f, 0.45f},
        .fireScale = 0.045f,
        .fireSpeed = 3.2f,
        .fireAmount = 0.9f,
        .fireInner = 56,
        .fireOuter = 125,
        .glowColor = {1.0f, 0.35f, 0.0f},
        .glowRadius = 80,
        .glowAmount = 0.12f,
        .glowPulse = 0,
        .specular = 0.25f,
        .scanlines = 0,
        .lids = true,
        .lidColor = {0.10f, 0.05f, 0.04f},
        .lidEdge = {1.0f, 0.35f, 0.02f},
        .gazeRange = 40,
        .saccadeRate = 0.9f,
        .blinkRate = 8,
        .jitter = 1.2f,
        .snap = false,
    },
    {
        .id = "alien",
        .name = "Alien",
        .sclera = {0.02f, 0.03f, 0.04f},
        .scleraEdge = {0.0f, 0.0f, 0.0f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 108,
        .irisInner = {0.02f, 0.30f, 0.28f},
        .irisOuter = {0.30f, 0.04f, 0.40f},
        .limbus = {0.01f, 0.01f, 0.02f},
        .limbusWidth = 14,
        .striation = 1.0f,
        .striationFreq = 14,
        .irisSwirl = 0.35f,
        .pupilShape = PupilShape::Round,
        .pupilColor = {0.0f, 0.0f, 0.0f},
        .pupilMin = 42,
        .pupilMax = 70,
        .slitHeight = 0,
        .fire = FireMode::None,
        .fireLow = kBlack, .fireMid = kBlack, .fireHigh = kBlack,
        .fireScale = 0, .fireSpeed = 0, .fireAmount = 0, .fireInner = 0, .fireOuter = 0,
        .glowColor = {0.1f, 0.9f, 0.6f},
        .glowRadius = 30,
        .glowAmount = 0.0f,
        .glowPulse = 0,
        .specular = 0.7f,
        .scanlines = 0,
        .lids = true,
        .lidColor = {0.34f, 0.44f, 0.36f},
        .lidEdge = {0.12f, 0.18f, 0.14f},
        .gazeRange = 14,
        .saccadeRate = 1.6f,
        .blinkRate = 3,
        .jitter = 1.5f,
        .snap = false,
    },
    {
        .id = "sauron",
        .name = "Sauron",
        .sclera = {0.0f, 0.0f, 0.0f},
        .scleraEdge = {0.0f, 0.0f, 0.0f},
        .veins = 0,
        .rings = 0,
        .irisRadius = 96,
        .irisInner = {1.00f, 0.72f, 0.18f},
        .irisOuter = {0.70f, 0.10f, 0.0f},
        .limbus = {0.25f, 0.02f, 0.0f},
        .limbusWidth = 20,
        .striation = 0.8f,
        .striationFreq = 60,
        .irisSwirl = 0.25f,
        .pupilShape = PupilShape::Slit,
        .pupilColor = {0.0f, 0.0f, 0.0f},
        .pupilMin = 5,
        .pupilMax = 14,
        .slitHeight = 0.95f,
        .fire = FireMode::Radial,
        .fireLow = {0.60f, 0.04f, 0.0f},
        .fireMid = {0.95f, 0.30f, 0.02f},
        .fireHigh = {1.0f, 0.80f, 0.35f},
        .fireScale = 1.6f,
        .fireSpeed = 1.6f,
        .fireAmount = 1.0f,
        .fireInner = 60,
        .fireOuter = 130,
        .glowColor = {1.0f, 0.5f, 0.1f},
        .glowRadius = 28,
        .glowAmount = 0.8f,
        .glowPulse = 0.35f,
        .specular = 0,
        .scanlines = 0,
        .lids = false,
        .lidColor = kBlack,
        .lidEdge = kBlack,
        .gazeRange = 14,
        .saccadeRate = 0.25f,
        .blinkRate = 0,
        .jitter = 0.4f,
        .snap = false,
    },
    {
        .id = "terminator",
        .name = "Terminator",
        .sclera = {0.20f, 0.20f, 0.22f},
        .scleraEdge = {0.06f, 0.06f, 0.07f},
        .veins = 0,
        .rings = 1.0f,
        .irisRadius = 50,
        .irisInner = {1.0f, 0.10f, 0.03f},
        .irisOuter = {0.18f, 0.0f, 0.0f},
        .limbus = {0.03f, 0.03f, 0.03f},
        .limbusWidth = 8,
        .striation = 0,
        .striationFreq = 0,
        .irisSwirl = 0,
        .pupilShape = PupilShape::None,
        .pupilColor = kBlack,
        .pupilMin = 0,
        .pupilMax = 0,
        .slitHeight = 0,
        .fire = FireMode::None,
        .fireLow = kBlack, .fireMid = kBlack, .fireHigh = kBlack,
        .fireScale = 0, .fireSpeed = 0, .fireAmount = 0, .fireInner = 0, .fireOuter = 0,
        .glowColor = {1.0f, 0.05f, 0.0f},
        .glowRadius = 34,
        .glowAmount = 1.3f,
        .glowPulse = 0.5f,
        .specular = 0.35f,
        .scanlines = 0.5f,
        .lids = false,
        .lidColor = kBlack,
        .lidEdge = kBlack,
        .gazeRange = 30,
        .saccadeRate = 0.5f,
        .blinkRate = 4,
        .jitter = 0,
        .snap = true,
    },
};

constexpr int kThemeCount = sizeof(kThemes) / sizeof(kThemes[0]);

}  // namespace

const ThemeSpec* themeById(const char* id) {
  for (const auto& t : kThemes)
    if (strcmp(t.id, id) == 0) return &t;
  return nullptr;
}

const ThemeSpec* themeAt(int index) {
  return (index >= 0 && index < kThemeCount) ? &kThemes[index] : nullptr;
}

int themeCount() { return kThemeCount; }

}  // namespace eyes
